name: Deploy to Amazon EC2

on:
  push:
    branches: [ main ] # Esto hace que se ejecute al subir cambios

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/evaluacion-parcial-2
            sudo docker-compose down
            sudo docker-compose up --build -d